update inspections
set status                    = 2,
    type                      = :type,
    resolution                = :resolution,
    limit_reason              = :limit_reason,
    method                    = :method,
    method_by                 = :method_by,
    reason_type               = :reason_type,
    reason_description        = :reason_description,
    is_restriction_checked    = :is_restriction_checked,
    is_violation_detected     = :is_violation_detected,
    is_expense_available      = :is_expense_available,
    violation_description     = :violation_description,
    is_unauthorized_consumers = :is_unauthorized_consumers,
    unauthorized_description  = :unauthorized_description,
    unauthorized_explanation  = :unauthorized_explanation,
    inspect_at                = now(),
    energy_action_at          = :energy_action_at
where id = :id
returning id,
    task_id,
    status,
    type,
    resolution,
    limit_reason,
    method,
    method_by,
    reason_type,
    reason_description,
    is_restriction_checked,
    is_violation_detected,
    is_expense_available,
    violation_description,
    is_unauthorized_consumers,
    unauthorized_description,
    unauthorized_explanation,
    inspect_at,
    energy_action_at,
    created_at,
    updated_at;
